[package]
name = "listing_17_10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
listing_17_7 = {path = "../listing_17_7"}