[package]
name = "personnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorized = "1.0.0"
console-menu = "0.1.3"
console-utils = "1.5.9"
